### ISSUE TITLE
District code substring: "" is an invalid format.

### ISSUE THREAD

**Issue by ryanoillataguerre** [chrisdevwords/congressional-district-finder#5]
Just tried a request to test out the result format, but get an error every time. Changed it to async/await syntax and get the same thing. 

This is my JS code

```javascript
const findUserDistrict = (lat, long) => {
	finder
		.getDistrictByLatLng(lat, long)
		.then(function(result) {
			console.log(result.district.name);
			console.log(result.district.districtCode);
		})
		.catch(function(err) {
			console.log(err.message);
		});
};

findUserDistrict(21.3069, -157.8583);
```

and this is what I get as a result:

```
Error: District code substring: "" is an invalid format.
    at parseDistrictCode (/Users/ryan/code/breakdown/breakdown-api/node_modules/house-gov-page-scraper/dist/house/gov/getDistrictsInZip.js:37:15)
    at Array.map (<anonymous>)
    at scrapePage (/Users/ryan/code/breakdown/breakdown-api/node_modules/house-gov-page-scraper/dist/house/gov/getDistrictsInZip.js:68:17)
    at /Users/ryan/code/breakdown/breakdown-api/node_modules/house-gov-page-scraper/dist/house/gov/getDistrictsInZip.js:84:16
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Would really appreciate a solution to this, as I'm launching a time-sensitive app for this election.

**Comment by ryanoillataguerre** [comment]
Also, just ran a test on the module, and looks like it's failing in multiple areas.

```
> congressional-district-finder@0.1.1 test /Users/ryan/Desktop/testingnpm/congressional-district-finder
> nyc mocha ./test



  #flattenMultiPolygon
    with a contiguous district 
      ✓ extracts an array with one polygon
      ✓ extracts an array with one polygon of lat,lng coordinates
    with a contiguous state
      ✓ extracts an array with one polygon
      ✓ extracts a single polygon containing lat,lng coordinates
    with a multi-shape district 
      ✓ extracts an array of polygons
      ✓ extracts an array of polygons, each containing lat,lng coordinates
    with a multi-shape state
      ✓ extracts an array of polygons
      ✓ extracts an array of polygons, each containing lat,lng coordinates
    with a null value
      ✓ throws a helpful error

  #isLatLngInMultiPolygon
    with a complex district polygon parsed from geoJSON
      ✓ correctly returns true
      ✓ correctly returns false
    with a complex state parsed from geoJSON
      ✓ correctly returns true
      ✓ correctly returns false (62ms)

  #isLatLngInPolygon
    with a district polygon parsed from geoJSON
      ✓ correctly returns true
      ✓ correctly returns false
    with an invalid lat,lng
      ✓ throws an Invalid Coordinates Error

  #isValidGeoCoordinates
    with an array of float coordinates from geoJSON
      ✓ correctly returns true
    with an array of string coordinates from geoJSON
      ✓ correctly returns true
    with an array not matching the required format
      ✓ returns false
    with an array containing a null value
      ✓ returns false

  #parseGeoCoordinates
    with an array of coordinates from geoJSON
      ✓ correctly formats an object for geolib
    with an array not matching the required structure
      ✓ throws an error
    with a comma delimited string
      ✓ correctly parses a lat,lng object
    with a malformed string
      ✓ throws an error

  #getDistrictShape
    with a valid district id
      ✓ returns an array of multipolygon coordinates
      ✓ returns the district name and code
    with an invalid district id
      - throws an error without making a request
      ✓ throws an error
      ✓ throws a message indicating the district wasn't found.
    with a non 404 error
      ✓ rejects the promise with the statusCode
      ✓ rejects the promise with the message

  #parseDistrictShape
    with JSON in the expected format
      ✓ parses the name from shape json
      ✓ parses the districtCode from shape json
      ✓ parses the polygons from shape json
    with JSON in an unexpected format
      ✓ throws a helpful error

  #getDistricts
    by default
      ✓ returns a list of all congressional districts
      ✓ passes a default user agent in the headers
    when passed a custom user-agent
      ✓ it overrides the default in the headers
    when passed an etag in customOptions
      ✓ handles a 304
      ✓ passes the etag in the request headers
    when passed an invalid/expired eTag
      ✓ resolves a 200 w/ a new eTag

  #getDistrictsByState
    with a valid state
      ✓ returns a list of districts
    with an invalid state
      ✓ throws an error

  #getStateShape
    result of a valid state code
      ✓ contains an array of coordinates
    with a invalid state code
      - throws an error without making a request
      ✓ handles a 404

  #parseStateShape
    ✓ parses the polygons from shape json

  Google geocode helper
    #getLatLngFromAddress
      with a street number, city and state in the US
        ✓ can get the zip code
        ✓ can get the geo coordinates
      with the name of an american neighborhood
        ✓ can get the country
        ✓ can get the geo coordinates
      with the name of an american city
        ✓ can get the geo coordinates
        ✓ can get the country
      with an address outside the country
        ✓ can get the country
        ✓ can get the geo coordinates
      with a string that yields no results
        ✓ rejects with a 404 and message
      with a response indicating an invalid request
        ✓ rejects with a 400 and message

  Google geocode helper
    #getStateZipFromLatLng
      with a valid lat,lng
        ✓ can extract a state id
        ✓ can extract a zip code
        ✓ can extract a country
      with a lat,lng that yields no results
        ✓ rejects with a 404 and message
      with an invalid lat,lng
        ✓ rejects with an invalid lat,lng error without making a request
        ✓ rejects with an invalid lat,lng error with the correct status code
        ✓ rejects with an invalid lat,lng error with an informative message
      with an error response other than 404
        ✓ handles the error
        ✓ rejects with an error message
        ✓ only makes one request

  #parseJSON
    with a successful US result
      ✓ can extract the country
      ✓ can extract a state id
      ✓ can extract a zip code
      ✓ can extract the lat, lng
    with a result outside the US
      ✓ can extract the country
      ✓ can extract the lat, lng
    with a result in a US Territory
      ✓ can extract the country
      ✓ can extract the lat, lng

  #checkLatLngInDistrict
    when checking a lat,lng in a district
      ✓ resolves a promise saying it matches
      ✓ resolves a promise with the districtCode
      ✓ resolves a promise with the district name
    when checking a lat,lng not in a district
      ✓ resolves a promise saying it doesn't match
    when checking a lat,lng against an invalid district
      ✓ rejects a promise with a 404
    when checking an invalid lat,lng against a district
      ✓ rejects a promise with an invalid coordinates error

  #checkLatLngInDistricts
    with a lat lng residing in one district of an array
      ✓ finds the correct district
      ✓ only makes the necessary http requests
    with a lat lng that doesn't reside in any of the provided districts
      ✓ throws an informative error
      ✓ checks every single district
    with an empty array
      ✓ throws an informative error
      ✓ throws an error without making an http request
    with a value of null for districts
      ✓ throws an informative error
      ✓ throws an error without making an http request

  #checkLatLngInState
    when checking a lat,lng in a state
      ✓ resolves a promise saying it matches
    when checking a lat,lng not in a state
      ✓ resolves a promise saying it doesn't match
    when checking a lat,lng against an invalid state
      ✓ rejects a promise with a 404
    when checking an invalid lat,lng against a state
      ✓ rejects a promise with an invalid coordinates error

  #getDistrictByAddress
    with an american street address
      1) can find the district
    with the name of a city
      ✓ throws a 400 for being too vague (118ms)
    with an address outside the country
      ✓ rejects with a 404 (731ms)

  #getDistrictByLatLng
    with latitude and longitude
      2) can find a district in Westerville, OH
      3) can find a district in Alaska
    with a latititude and longitude outside the US
      ✓ rejects the promise with a helpful error (211ms)
      ✓ only makes a single http request (136ms)
    with invalid lat lng coordinates
      ✓ throws an informative error
      ✓ doesn't make any http requests


  97 passing (10s)
  2 pending
  3 failing

  1) #getDistrictByAddress with an american street address can find the district:
     Error: District code substring: "" is an invalid format.
      at parseDistrictCode (node_modules/house-gov-page-scraper/dist/house/gov/getDistrictsInZip.js:37:15)
      at Array.map (<anonymous>)
      at scrapePage (node_modules/house-gov-page-scraper/dist/house/gov/getDistrictsInZip.js:68:17)
      at node_modules/house-gov-page-scraper/dist/house/gov/getDistrictsInZip.js:84:16
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) #getDistrictByLatLng with latitude and longitude can find a district in Westerville, OH:
     Error: District code substring: "" is an invalid format.
      at parseDistrictCode (node_modules/house-gov-page-scraper/dist/house/gov/getDistrictsInZip.js:37:15)
      at Array.map (<anonymous>)
      at scrapePage (node_modules/house-gov-page-scraper/dist/house/gov/getDistrictsInZip.js:68:17)
      at node_modules/house-gov-page-scraper/dist/house/gov/getDistrictsInZip.js:84:16
      at process._tickCallback (internal/process/next_tick.js:68:7)

  3) #getDistrictByLatLng with latitude and longitude can find a district in Alaska:
     Error: District code substring: "" is an invalid format.
      at parseDistrictCode (node_modules/house-gov-page-scraper/dist/house/gov/getDistrictsInZip.js:37:15)
      at Array.map (<anonymous>)
      at scrapePage (node_modules/house-gov-page-scraper/dist/house/gov/getDistrictsInZip.js:68:17)
      at node_modules/house-gov-page-scraper/dist/house/gov/getDistrictsInZip.js:84:16
      at process._tickCallback (internal/process/next_tick.js:68:7)




=============================== Coverage summary ===============================
Statements   : 98.95% ( 189/191 )
Branches     : 100% ( 56/56 )
Functions    : 96.36% ( 53/55 )
Lines        : 98.81% ( 166/168 )
================================================================================
npm ERR! Test failed.  See above for more details.
```
